---
- name: Commit Configuration to devices
  juniper_junos_config:
    provider: "{{credentials.junos}}"
    load: "{{commit_mode | default('merge')}}"
    src: "{{junos_conf}}"
    diff: true
    diffs_file: "outputs/{{ inventory_hostname }}-diff.log"
    check: true
    commit: true